database:
  hostName: orangehrm-mysql
  hostPort: 3306
  databaseName: ohrmdb
  privilegedDatabaseUser: root
  privilegedDatabasePassword: orangehrm123
  useSameDbUserForOrangeHRM: y # y/n, if this field `n` fill `orangehrmDatabaseUser` and `orangehrmDatabasePassword`
  orangehrmDatabaseUser: ~
  orangehrmDatabasePassword: ~
  isExistingDatabase: n # y/n
  enableDataEncryption: n # y/n

organization:
  name: OrangeHRM
  country: US

admin:
  adminUserName: Admin
  adminPassword: Ohrm@1423
  adminEmployeeFirstName: OrangeHRM
  adminEmployeeLastName: Admin
  workEmail: admin@example.com
  contactNumber: ~
  registrationConsent: true

license:
  agree: y # y/n
